name: 'Notification action'
description: 'Notification reusable action'
author: 'Gutenberg Technology'

inputs:
  github-last-job-result:
    description: 'Slack color'
    required: true
  slack-webhook-url:
    description: 'Slack webhook url'
    required: false
  slack-channel:
    description: 'Slack channel'
    required: false
  slack-username:
    description: 'Slack user'
    required: false
  slack-icon:
    description: 'Slack icon'
    required: false
  slack-title:
    description: 'Slack title'
    required: false
  slack-message:
    description: 'Slack message'
    required: false
  slack-footer:
    description: 'Slack footer'
    required: false
    default: 'Gutenberg Technology'
  slack-markdown:
    description: 'Slackify markdown'
    required: false
    default: 'false'
  
runs:
  using: 'composite'
  steps:
    - name: Slack - Send Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ inputs.slack-webhook-url }}
        SLACK_CHANNEL: it_script
        SLACK_USERNAME: ${{ inputs.slack-username }}
        SLACK_COLOR: ${{ inputs.github-last-job-result }}
        SLACK_ICON: ${{ inputs.slack-icon }}
        SLACK_MESSAGE: ${{ inputs.slack-message }}
        SLACK_TITLE: ${{ inputs.slack-title }}
        SLACK_FOOTER: ${{ inputs.slack-footer }}
        SLACKIFY_MARKDOWN: ${{ inputs.slack-markdown }}

